### ISSUE TITLE
Убрать из репо *.iml, .idea

### ISSUE THREAD

**Issue by coursar** [Alanrus/06-myozon#2]

**Comment by coursar** [comment]
и target тоже

**Comment by Alanrus** [comment]
Ильназ, у меня что-то пошло не так с gitignore. Файл есть в проекте, но не работает. когда я клонировал содержимое в новый проект, то gitignore прекрасно работает. в действующем проекте не работает gitignore, не пойму что сломал. 
Может мне новый проект в git залить? 
п.с. все предыдущие ошибки исправил кроме gitignore.

**Comment by Alanrus** [comment]
Нижеприведенные действия тоже делал. каталог target так и остался в gitignore.

Если вы всё-таки залили мусор, то в IDEA нужно:
Alt + F12
В консоли выполнить команды:
git rm --cached -r .idea
git rm --cached -r *.iml
После чего сделать git commit + git push

**Comment by coursar** [comment]
Так сделайте и для `target` тоже:
`git rm --cached -r target`
После чего сделать `git commit` + `git push`
