### ISSUE TITLE
Там только Lego продаются?

### ISSUE THREAD

**Issue by coursar** [Alanrus/06-myozon#4]
https://github.com/Alanrus/06-myozon/blob/8c811573116e3775afc092d91c4fb4e5c24fee75/src/main/java/ru/itpark/Lego.java#L3

**Comment by Alanrus** [comment]
в ТЗ - картинке были исключительно lego :-) 
Если надо добавить другие классы, то, пожалуйста, сообщите и я сделаю.

**Comment by coursar** [comment]
Ок
